### ISSUE TITLE
Match orders >> Prediction of ratings fails

### ISSUE THREAD

**Issue by ariehead** [minj/foxtrick#1516]
## Short description of the problem
- Pushing the "prediction" button in Match Orders template shows all "non-existent"ratings at every position when the checkbox "stamina correction" is enabled.
- Furthermore "Hatstats" and "Loddarstats" shows 0 ratings regardless of checkboxes. 

## What steps will reproduce the problem?
Disabling the "stamina correction" checkbox at least shows ratings but Hatstats and Loddar remain 0 (as described in problem description).

## What is the expected behaviour? What is the actual behaviour? Please provide any relevant screenshots.
![01-stamina_checked](https://user-images.githubusercontent.com/30177945/28213336-eacb06c4-68a5-11e7-8bd7-b225eb88d3c4.jpg)
![02-stamina_unchecked](https://user-images.githubusercontent.com/30177945/28213340-edf43adc-68a5-11e7-9e9e-5ef0fac6c542.jpg)

Apologies for ratings in Dutch language: "niet-bestaand" equals "non-existent" !

Expected behaviour: 
- shows expected ratings but bit downsized because of loss of "stamina" when "stamina correction" checkbox is checked.
- shows expected HatStats and LoddarStats instead of 0 ratings.

**Comment by marcodav** [comment]
For me it doesn't show expected rating even if I uncheck the "stamina correction" checkbox.

**Comment by ariehead** [comment]
@marcodav : Doesn't it even predict ratings in terms of text ? 

In my case it shows at least some prediction in textual form at the 7 sections (3x defense, midfield, 3x attack) but the corresponding numbers remain 0.

My guess is hattrick itself changed something which causes Foxtrick to fail; these predictions worked like a charm about a week ago ! 
Probably a new Foxtrick version has to be released to fix this (if possible)

**Comment by marcodav** [comment]
Yes It does text but not numbers, it was working without problems last week. 

		
		

		Ottieni Outlook per iOS
	




On Sat, Jul 15, 2017 at 2:39 PM +0200, "ariehead" <notifications@github.com> wrote:












@marcodav : Doesn't it even predict ratings in terms of text ?


In my case it shows at least some prediction in textual form at the 7 sections (3x defense, midfield, 3x attack) but the corresponding numbers remain 0.


My guess is hattrick itself changed something which causes Foxtrick to fail; these predictions worked like a charm about a week ago !

Probably a new Foxtrick version has to be released to fix this (if possible)

**Comment by guytzhak** [comment]
Have the same problem...

**Comment by rferromoreno** [comment]
Yes. It might be something that Hattrick devs changed from the match orders page.

For the 0.0 problem, I'm not sure, but I think the problem is right here, on **/content/matches/match-simulator.js** at line **709**

`var rating = overlayRating.dataset.rating;`

**Comment by ariehead** [comment]
@rferromoren 

Although I am a software developer myself I admit JavaScript is not my cup of tea but I think you have given the right direction.

I am convinced that Hattrick changed something to the match orders page because it worked perfectly a week ago and now it doesn't with the same Foxtrick build so it has te bo Hattrick itself that has changed. Analyses of what has changed within HT with regard to the match orders has te be done in order to fix this issue in the next Foxtrick build.

**Comment by murko69** [comment]
HT-Tasos mentioned on Global that they had updated the third-party library (jQuery) to a new version so maybe it's a pretty "easy fix" for @minj  if/when he has the time. ;)
[post=17103644.519]

**Comment by ariehead** [comment]
@murko69  Thanks for sharing that important info with us !
Hope @minj has time to fix this issue indeed ;)

**Comment by mattadiro** [comment]
Hey ...  maybe something new for this issue ?  at least a temp solution ?

**Comment by guytzhak** [comment]
14 days ago, hattrick create new commit to their code...mybe its cause the issue:
https://github.com/jetwitaussi/PHT/commit/d43b82e3355d035c6245a18fd2d967bc541b40f1
name: Handle matchOrders v3.0. Add bench players, kickers, captain and set pieces

**Comment by ariehead** [comment]
Don´t know what happened (recompile of code because of new library?) but it is solved !
I am closing this issue (to reduce the number of issues for the developers).

**Comment by minj** [comment]
I'll reopen this to remind me to investigate it when I allocate time for Foxtrick next

**Comment by ariehead** [comment]
@minj good luck investigating: hope this thread will help you !

**Comment by guytzhak** [comment]
the problem still there! the offensive rating of team A is calculate offensive rating of team B istaed their defensive ratings:

screenshot:
http://prntscr.com/fyc1wt

**Comment by ariehead** [comment]
@guytzhak thats another (new) issue

**Comment by minj** [comment]
@guytzhak I thought 'attack vs defence' toggle was obvious...

I am closing this since it works and there is not really anything to investigate as the problem was reverted by HTs.

`dataset.rating` is automatically available as a property in DOM if an attribute `data-rating` is set on the element in question. 

This could have broken, no doubt, in case this supposed jQuery update changed the way these variables are stored in jQuery. 🤷‍♂️
